### ISSUE TITLE
TravisCI community support

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4043]
I have just drafted a [PR](https://github.com/travis-ci/travis-build/pull/406) to TravisCI to add community support of our beloved haxe language.

In addition to myself, we need 2 more maintainers, to be listed in the TravisCI doc, such that they can find someone to fix problems. The maintainers probably would mostly handle issues related to setting up haxe.
@waneck I'm using your build server to download nightly builds and you're maintaining travis-hx. Would you mind to be listed?
@ncannasse I think you're the only one who know all the setup stuff (especially for neko). Any problem if I add you to the list?

Anyone familiar with docker/vagrant who are interested in helping please join since we will probably create a custom haxe environment :)

**Comment by waneck** [comment]
I'd be thrilled to help, @andyli !

**Comment by andyli** [comment]
Great! I've just added you as a maintainer in the haxe build script over the [PR](https://github.com/travis-ci/travis-build/pull/406/files).

**Comment by Simn** [comment]
You can add me pro forma.

**Comment by andyli** [comment]
Added! Thanks!

**Comment by andyli** [comment]
Initial support [has been add](http://blog.travis-ci.com/2015-04-07-haxe-now-available-on-travis-ci/) :D

**Comment by Simn** [comment]
Very nice!

I've tried it with hxparse and it works nicely with this file: https://github.com/Simn/hxparse/blob/travis/.travis.yml

What's the easiest way to get a set of hxml files into a build matrix so they show up as distinct builds?

**Comment by andyli** [comment]
Probably with [matrix: include:](http://docs.travis-ci.com/user/build-configuration/#Explicit-inclusion-of-jobs-into-the-build-matrix)
```yaml
matrix:
  include:
    - hxml:
      - build-neko.hxml
    - hxml:
      - build-macro.hxml
```

**Comment by Simn** [comment]
Now I get `The command "curl -s -L --retry 3 'http://haxe.org/website-content/downloads/["development"]/downloads/haxe-["development"]-linux64.tar.gz' | tar -C ~/haxe -x -z --strip-components=1 -f -" failed and exited with 2 during .`

**Comment by andyli** [comment]
This is some tricky implementation detail. The `haxe:` key has to be placed within each of the `matrix: include:` items, like this:
```yaml
language: haxe

install:
  - haxelib install unifill

matrix:
  include:
    - haxe: development
      hxml:
        - build-neko.hxml
    - haxe: development
      hxml:
        - build-macro.hxml
```

Reported at https://github.com/travis-ci/travis-ci/issues/3638 to see if Travis can do anything about that or not.
